'use client';
import Link from 'next/link';
import {createContext,useContext,useState,Fragment} from 'react';
import {ArrowUpRight,Heart,Leaf,BookOpen,Flower2,Menu,X,MapPin,Instagram,Mail,Plus,Minus,Check,MoveRight} from 'lucide-react';
import Motion from './motion';
import HeroSlider from './hero-slider';
import defaults,{type SiteContent,type LinkValue,type IntroValue,type ImageValue} from '../content/types';
const Content=createContext<SiteContent>(defaults);
const useSite=()=>useContext(Content);
const icons=[Heart,BookOpen,Leaf,Flower2];
function Picture({image,...props}:{image:ImageValue;className?:string;loading?:'lazy'|'eager'}){return <img src={image.src} alt={image.alt} {...props}/>}
function Lines({text}:{text:string}){return <>{text.split('\n').map((line,i)=><Fragment key={i}>{i>0&&<br/>}{line}</Fragment>)}</>}
function Heading({title,accent}:{title:string;accent?:string}){return <h2><Lines text={title}/>{accent&&<><br/><em>{accent}</em></>}</h2>}
function Button({link,light=false}:{link:LinkValue;light?:boolean}){return <Link className={'button '+(light?'light':'')} href={link.href}>{link.label}<ArrowUpRight size={16}/></Link>}
function TextLink({link}:{link:LinkValue}){return <Link className="text-link" href={link.href}>{link.label}<MoveRight size={20}/></Link>}
function Eyebrow({children}:{children:React.ReactNode}){return <div className="eyebrow"><span/>{children}</div>}
function PageIntro({data}:{data:IntroValue}){return <section className="page-intro"><Eyebrow>{data.eyebrow}</Eyebrow><h1><Lines text={data.title}/><br/><em>{data.accent}</em></h1><p>{data.description}</p></section>}
function CTA(){const c=useSite().callToAction;return <section className="cta"><div><p className="overline">{c.eyebrow}</p><Heading title={c.title}/><p>{c.description}</p></div><Button link={c.button} light/></section>}
function PhotoStory(){const c=useSite().gallery;if(!c.enabled)return null;return <section className="photo-story section"><div className="section-heading"><div><Eyebrow>{c.eyebrow}</Eyebrow><Heading title={c.title} accent={c.accent}/></div><p>{c.description}</p></div><div className="story-grid">{c.items.map((item,i)=><figure key={i}><Picture image={item.image} loading="lazy"/><figcaption><span>{item.label}</span>{item.caption}</figcaption></figure>)}</div>{c.note&&<p className="photo-caption">{c.note}</p>}</section>}
function Testimonials(){const c=useSite().testimonials;const [index,setIndex]=useState(0);if(!c.enabled||!c.items.length)return null;const selected=c.items[index%c.items.length];return <section className="testimonials"><Flower2 size={31} strokeWidth={1}/><p className="overline">{c.eyebrow}</p><h2>“{selected.quote}”</h2><p className="muted">{selected.attribution}</p><div className="dots">{c.items.map((_,i)=><button key={i} aria-label={`Show testimonial ${i+1}`} aria-pressed={index===i} className={index===i?'active':''} onClick={()=>setIndex(i)}/>)}</div></section>}
function Services({full=false}:{full?:boolean}){const c=useSite().packages;return <section className="section services"><div className="section-heading"><div><Eyebrow>{c.eyebrow}</Eyebrow><Heading title={c.title} accent={c.accent}/></div><p>{c.description}</p></div><div className="package-grid">{c.items.map((p,i)=>{const Icon=icons[i%icons.length];return <article className={'package '+(p.featured?'featured':'')} key={i}><Picture className="package-photo" image={p.image} loading="lazy"/><div className="package-top"><Icon size={29} strokeWidth={1.2}/><span>{String(i+1).padStart(2,'0')}</span></div><p className="overline">{p.tag}</p><h3>{p.name}</h3>{p.price&&<p className="package-price">{p.price}</p>}<p>{p.description}</p>{full&&<ul>{p.features.map((item,j)=><li key={j}><Check size={15}/>{item}</li>)}</ul>}<Link href={full?`/contact?package=${encodeURIComponent(p.name)}`:'/services'}>{full?c.inquireLabel:c.exploreLabel}<ArrowUpRight size={17}/></Link></article>})}</div>{full&&c.note&&<p className="content-note">{c.note}</p>}</section>}
function Home(){const c=useSite().home;return <><section className="hero"><div className="hero-copy"><Eyebrow>{c.hero.eyebrow}</Eyebrow><h1><Lines text={c.hero.title}/><br/><em>{c.hero.accent}</em></h1><p>{c.hero.description}</p><Button link={c.hero.button}/><div className="location"><MapPin size={14}/>{c.hero.location}</div></div><HeroSlider content={c.hero}/><span className="hero-index">{c.hero.caption}</span></section><div className="values">{c.values.map((value,i)=>{const Icon=icons[i%icons.length];return <Fragment key={i}>{i>0&&<i/>}<span><Icon/>{value}</span></Fragment>})}</div><section className="philosophy section"><p className="overline">{c.philosophy.eyebrow}</p><Heading title={c.philosophy.title} accent={c.philosophy.accent}/><p>{c.philosophy.description}</p><TextLink link={c.philosophy.button}/></section><Services/><section className="about-preview section"><div className="about-image"><Picture image={c.aboutPreview.image}/><span className="little-stamp">{c.aboutPreview.stampTop}<br/><Heart size={23}/><br/>{c.aboutPreview.stampBottom}</span></div><div><Eyebrow>{c.aboutPreview.eyebrow}</Eyebrow><Heading title={c.aboutPreview.title} accent={c.aboutPreview.accent}/>{c.aboutPreview.paragraphs.map((p,i)=><p key={i}>{p}</p>)}<Button link={c.aboutPreview.button}/><span className="photo-caption">{c.aboutPreview.caption}</span></div></section><PhotoStory/><Testimonials/><CTA/></>}
function About(){const c=useSite().about;return <><PageIntro data={c.intro}/><section className="section about-preview"><div className="about-image"><Picture image={c.journey.image}/><span className="photo-caption">{c.journey.caption}</span></div><div><Eyebrow>{c.journey.eyebrow}</Eyebrow><Heading title={c.journey.title} accent={c.journey.accent}/><p>{c.journey.description}</p>{c.journey.note&&<p className="content-note">{c.journey.note}</p>}{c.storySections.map((s,i)=><Fragment key={i}><h3>{s.title}</h3><p>{s.description}</p></Fragment>)}</div></section><section className="section two-column"><div><Eyebrow>{c.areas.eyebrow}</Eyebrow><Heading title={c.areas.title} accent={c.areas.accent}/><p>{c.areas.description}</p><Button link={c.areas.button}/></div><div className="verse"><Flower2/><p className="overline">{c.verses.eyebrow}</p>{c.verses.items.map((v,i)=><Fragment key={i}><h3>“{v.quote}”</h3><p>{v.reference}</p></Fragment>)}<p>{c.verses.note}</p></div></section><CTA/></>}
function Why(){const c=useSite().why;const [open,setOpen]=useState<number|null>(0);return <><PageIntro data={c.intro}/><section className="section"><div className="package-grid">{c.benefits.map((b,i)=><article className="package" key={i}><span className="overline">{String(i+1).padStart(2,'0')} / {c.benefitLabel}</span><h3>{b.title}</h3><p>{b.description}</p></article>)}</div><div className="research"><Heading title={c.research.title} accent={c.research.accent}/><p>{c.research.description}</p><TextLink link={c.research.button}/></div><div className="faq"><Eyebrow>{c.faqEyebrow}</Eyebrow><Heading title={c.faqTitle} accent={c.faqAccent}/>{c.questions.map((q,i)=><div className="faq-item" key={i}><button onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i} aria-controls={`answer-${i}`}>{q.question}{open===i?<Minus size={19}/>:<Plus size={19}/>}</button>{open===i&&<p id={`answer-${i}`}>{q.answer}</p>}</div>)}</div></section><PhotoStory/><Testimonials/><CTA/></>}
function ServicePage(){const c=useSite().services;return <><PageIntro data={c.intro}/><Services full/><section className="section extras"><div><Eyebrow>{c.extras.eyebrow}</Eyebrow><Heading title={c.extras.title} accent={c.extras.accent}/></div><div><p>{c.extras.description}</p><Button link={c.extras.button}/></div></section><section className="section process"><Eyebrow>{c.process.eyebrow}</Eyebrow><Heading title={c.process.title} accent={c.process.accent}/><div className="package-grid">{c.process.steps.map((s,i)=><div key={i}><span className="step">{String(i+1).padStart(2,'0')}</span><h3>{s.title}</h3><p>{s.description}</p></div>)}</div></section><PhotoStory/><Testimonials/><CTA/></>}
function Contact(){const site=useSite();const c=site.contact;const f=c.form;const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);return <><PageIntro data={c.intro}/><section className="section contact-grid"><div><Eyebrow>{c.consultation.eyebrow}</Eyebrow><Heading title={c.consultation.title} accent={c.consultation.accent}/><p>{c.consultation.description}</p>{c.bookingUrl&&<Button link={{label:c.bookingLabel,href:c.bookingUrl}}/>}<div className="contact-detail"><MapPin size={20}/><span>{c.location}</span></div><div className="contact-detail"><Mail size={20}/>{c.email?<a href={`mailto:${c.email}`}>{c.email}</a>:<span>{c.emailPlaceholder}</span>}</div><div className="contact-detail"><Instagram size={20}/>{c.instagramUrl?<a href={c.instagramUrl} target="_blank" rel="noreferrer">Instagram</a>:<span>{c.instagramPlaceholder}</span>}</div>{c.note&&<p className="content-note">{c.note}</p>}</div><form onSubmit={async e=>{e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setStatus('');setSent(false);try{const data=Object.fromEntries(new FormData(form));const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error);setSent(true);setStatus(f.successMessage);form.reset();}catch(error){setStatus(error instanceof Error?error.message:'Your message was not sent. Please try again.');}finally{setBusy(false);}}}><h3>{f.title}</h3><div className="form-row"><label>{f.nameLabel}<input required maxLength={150} name="name" autoComplete="name" placeholder={f.namePlaceholder}/></label><label>{f.emailLabel}<input required maxLength={254} name="email" type="email" autoComplete="email" placeholder={f.emailPlaceholder}/></label></div><div className="form-row"><label>{f.dueDateLabel}<input name="dueDate" type="date"/></label><label>{f.serviceLabel}<select name="service" defaultValue=""><option value="" disabled>{f.servicePlaceholder}</option>{[...site.packages.items.map(p=>p.name),...f.extraOptions].map((v,i)=><option key={i}>{v}</option>)}</select></label></div><label>{f.messageLabel}<textarea required name="message" maxLength={5000} rows={5} placeholder={f.messagePlaceholder}/></label><label className="slider-sr-only" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="form-note">{f.privacyNote}</p><button className="button" disabled={busy} type="submit">{busy?'Sending…':f.buttonLabel}<ArrowUpRight size={16}/></button>{status&&<div className={sent?'form-success':'form-error'} role="status">{sent&&<Check size={18}/>} {status}</div>}</form></section></>}
export default function DoulaSite({page,content=defaults}:{page:string;content?:SiteContent}){const [menu,setMenu]=useState(false);const b=content.brand;return <Content.Provider value={content}><Motion page={page}/><header><Link href="/" className="brand"><Picture image={b.logo}/></Link><nav className={menu?'nav open':'nav'} aria-label="Main navigation">{b.navigation.map((link,i)=><Link key={i} href={link.href} onClick={()=>setMenu(false)} className={(page==='home'?link.href==='/':link.href==='/'+page)?'current':''}>{link.label}</Link>)}<Link href={b.contactButton.href} className="nav-contact" onClick={()=>setMenu(false)}>{b.contactButton.label}<ArrowUpRight size={14}/></Link></nav><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header><main>{page==='home'?<Home/>:page==='about'?<About/>:page==='why-a-doula'?<Why/>:page==='services'?<ServicePage/>:<Contact/>}</main><footer><div className="footer-top"><Link href="/" className="brand"><Picture image={b.logo}/></Link><p><Lines text={b.footerText}/></p><TextLink link={b.contactButton}/></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {b.name}</span><span>{b.footerLocation}<span className="footer-flower">✳</span>{b.footerSignature}</span></div></footer></Content.Provider>}
